sudo: required
language: android


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gradle/native
    - $HOME/.gradle/daemon

    - node_modules

env:
  global:
    - ANDROID_API_LEVEL=26

android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.2
  - android-$ANDROID_API_LEVEL

before_script

script:
  - ./gradlew :sample:assembleRelease
  - ./gradlew :kin-core:testDebugUnitTest
  - ./gradlew :kin-core:assembleAndroidTest
  - - openssl aes-256-cbc -K $encrypted_78f5c5933ac8_key -iv $encrypted_78f5c5933ac8_iv -in secret.json.enc -out secret.json -d
  - wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-220.0.0-linux-x86_64.tar.gz
  - tar xf google-cloud-sdk-220.0.0-linux-x86_64.tar.gz
  - echo "y" | ./google-cloud-sdk/bin/gcloud components update beta
  - ./google-cloud-sdk/bin/gcloud auth activate-service-account --key-file secret.json
  - ./google-cloud-sdk/bin/gcloud firebase test android run  \
      --type instrumentation --app sample/build/outputs/apk/debug/sample-debug.apk \
      --test  kin-core/build/outputs/apk/androidTest/debug/kin-core-debug-androidTest.apk \
      --device model=Nexus5X,version=25,locale=en \
      --environment-variables coverage=true,coverageFile=/sdcard/tmp/code-coverage/connected/coverage.ec \
      --directories-to-pull=/sdcard/tmp


after_success:
  - bash <(curl -s https://codecov.io/bash)
